// Code generated by go-bindata. DO NOT EDIT.
// sources:
// migrations/1633685677_init.down.sql (32B)
// migrations/1633685677_init.up.sql (1.2kB)
// migrations/1668845636_settings.down.sql (379B)
// migrations/1668845636_settings.up.sql (530B)

package migrations

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _migrations1633685677_initDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x48\x2f\xcd\x8c\x4f\xce\xcf\x4b\xcb\x4c\xb7\x06\x04\x00\x00\xff\xff\x49\xa7\x32\xcb\x20\x00\x00\x00")

func migrations1633685677_initDownSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations1633685677_initDownSql,
		"migrations/1633685677_init.down.sql",
	)
}

func migrations1633685677_initDownSql() (*asset, error) {
	bytes, err := migrations1633685677_initDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/1633685677_init.down.sql", size: 32, mode: os.FileMode(0664), modTime: time.Unix(1665214714, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xe8, 0x16, 0x49, 0x52, 0xa1, 0x76, 0xbe, 0xd5, 0x80, 0x60, 0xe1, 0x4e, 0x86, 0x4b, 0xe4, 0xc, 0x6c, 0x14, 0x63, 0x58, 0x6a, 0x87, 0x3d, 0xd3, 0x42, 0xf3, 0xb0, 0xfe, 0x20, 0x2, 0x6f, 0x87}}
	return a, nil
}

var _migrations1633685677_initUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xb4\x93\x51\x6f\xb2\x30\x14\x86\xef\xf9\x15\xe7\x0e\x48\xbc\xf0\xfb\x32\xb7\x25\xbb\x42\xad\x5b\x23\xc2\x02\x75\xd1\x2b\xd2\xd0\x2a\xcd\x18\x10\xa8\x41\xff\xfd\x52\x50\x04\x67\x74\x8b\xdb\xb9\x20\xf4\xe4\x3d\x6f\xdb\xe7\x9c\x8e\x3c\x64\x11\x04\xc4\x1a\xda\x08\xf0\x04\x1c\x97\x00\x5a\x60\x9f\xf8\xb0\xde\x88\x20\x4c\x93\x95\x58\x6b\x86\x06\x00\x50\x8a\x84\xa5\x65\x50\x0a\x26\x23\x00\xec\x90\x4a\xed\xcc\x6d\x1b\xc6\x68\x62\xcd\x6d\x02\xff\xfa\xff\xef\x7a\x6d\x71\xc4\xc5\x3a\x92\xe7\xc5\x0f\xf7\x8f\x1d\xed\x16\xaa\x38\xab\x1d\xf4\x3b\xd2\xdd\x37\xa4\x61\xce\xa9\xe4\x2c\xa0\x52\xad\xc6\x16\x41\x04\xcf\x50\x55\x77\x90\x1a\x8c\x4a\x2e\xc5\x07\x37\xf4\x24\x2d\xf5\x1e\xe8\x71\x1a\xd2\x58\x65\x74\xd3\x6c\xac\x6b\xbf\x4d\xc6\x7e\xc9\x4f\x33\x9f\x34\x0d\x3b\x3e\xf2\x88\xba\x82\xdb\x42\x0d\x46\x9b\x72\xaf\x8b\xb1\x59\x6e\x9b\xbf\x9d\xa9\xbd\x59\xf6\x1c\xf9\x60\x54\xec\x2b\xa8\x0a\x01\x0c\xfa\x6a\x97\x0b\xfd\x2d\xd3\xfc\xbd\xc8\x68\xc8\xf7\xed\x15\x0c\x0e\x81\x1d\x82\x9e\x91\x07\xaf\x1e\x9e\x59\xde\x12\xa6\x68\x59\x33\xc8\x68\xce\x13\x19\x28\xe9\x41\x73\x31\x8e\xf4\x22\x5a\x04\x61\x24\x62\x06\x30\x74\x5d\xfb\x72\x99\xaa\x3c\x6d\xeb\xc4\xb2\x7d\x54\x7b\xc9\x5d\xc6\xf7\x32\x82\x16\x04\x46\x2f\x68\x34\x05\xa3\x4a\x63\x07\x0c\x7d\xa5\xd0\x17\xea\x93\x7f\xed\xa3\x14\x32\xe6\xc7\xea\x3a\xc9\xa8\xa4\x6d\xcb\xab\xc7\x6b\xec\x8a\x34\x97\x27\xd8\x7e\x76\xb1\xfd\xb8\xf2\x6d\x46\x13\xc6\x55\x13\x6e\x06\xd4\x1a\xfd\xce\x9c\x5e\x8d\x5b\x1f\xc6\x9f\xee\xa6\x9e\xcd\x67\x00\x00\x00\xff\xff\x4d\x4a\x45\x79\xb0\x04\x00\x00")

func migrations1633685677_initUpSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations1633685677_initUpSql,
		"migrations/1633685677_init.up.sql",
	)
}

func migrations1633685677_initUpSql() (*asset, error) {
	bytes, err := migrations1633685677_initUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/1633685677_init.up.sql", size: 1200, mode: os.FileMode(0664), modTime: time.Unix(1669023217, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x60, 0xf, 0x22, 0xd5, 0x76, 0xef, 0xe6, 0x6e, 0xa4, 0x9f, 0xe3, 0xd3, 0x87, 0xa0, 0xb0, 0xbc, 0x67, 0x3, 0xc2, 0xeb, 0x6b, 0xee, 0xb4, 0xe0, 0xa0, 0xd3, 0x3f, 0x48, 0x65, 0xb2, 0x30, 0xfe}}
	return a, nil
}

var _migrations1668845636_settingsDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x94\xcf\x4d\xce\x82\x40\x0c\xc6\xf1\x3d\xa7\xe8\x3d\x58\xf1\xbe\xce\x8e\x0f\x43\x70\xdd\xc0\x50\x87\x46\xa6\x45\xa6\x24\x7a\x7b\x63\xe2\xd2\xc5\x78\x80\x5f\x9e\xe7\x5f\xd5\x83\xeb\x61\xa8\xfe\x6a\x07\x89\xcc\x58\x42\x2a\x00\x00\x4e\x7d\x77\x86\xff\xae\xbe\x34\x2d\x24\x96\xb0\x12\xb2\x24\x1b\xc5\x53\x59\x64\x29\xaf\x22\xe4\x0d\x8d\x23\xe9\x61\x99\x6a\xa7\xfb\x41\xe9\x57\x25\x2a\x38\xad\xea\x6f\x2c\x01\x3f\xc3\xac\x92\xa9\x93\xee\x86\x91\x6c\xd1\x39\xe1\xf4\x44\x19\x63\x6e\x64\x1c\x1f\xb8\xaa\x6e\x38\xd3\x66\x4b\x59\x7c\x55\xd0\xbb\xb6\x6a\x1c\x0c\x1d\x84\x83\xdf\xff\xae\x1c\xca\x57\x00\x00\x00\xff\xff\x8c\x3b\x19\xa0\x7b\x01\x00\x00")

func migrations1668845636_settingsDownSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations1668845636_settingsDownSql,
		"migrations/1668845636_settings.down.sql",
	)
}

func migrations1668845636_settingsDownSql() (*asset, error) {
	bytes, err := migrations1668845636_settingsDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/1668845636_settings.down.sql", size: 379, mode: os.FileMode(0664), modTime: time.Unix(1669023217, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x78, 0xa4, 0x33, 0xf7, 0x12, 0x45, 0xf2, 0xea, 0x41, 0xfc, 0xe1, 0x1c, 0x5d, 0x54, 0xf2, 0x98, 0x36, 0x99, 0x26, 0x30, 0x7d, 0x3e, 0x80, 0xbe, 0xd, 0x39, 0xdf, 0xae, 0x24, 0xb3, 0xd1, 0xbb}}
	return a, nil
}

var _migrations1668845636_settingsUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xa4\xd0\xc1\x4a\x03\x31\x10\x06\xe0\xfb\x3e\xc5\x3c\x82\xe2\xb1\xa7\xd4\x8d\x20\xa4\x09\x2c\xd9\xf3\xb0\x4d\xc7\x34\xb8\x99\xa9\xcd\x2c\xe8\xdb\x0b\xa2\x20\x88\x74\x61\xaf\xc3\xcf\xc7\xfc\xbf\x71\xd1\x0e\x10\xcd\xde\x59\xc8\x4b\xc1\x24\xfc\x52\x72\x07\x00\x30\x58\x6f\x0e\x16\x62\x80\x46\xaa\x85\x73\xdb\x75\xdd\xef\xfc\xcf\xf9\x2b\x6d\xfa\x1e\x1e\x83\x1b\x0f\x1e\x5a\xe1\x3c\x13\x16\x6e\x3a\x71\x22\xd8\x87\xe0\xc0\x87\x08\x7e\x74\x0e\x7a\xfb\x64\x46\x17\x21\x0e\xa3\xdd\xad\xf2\x92\x30\x53\x52\xd4\x52\x49\x16\x85\x67\x1f\xff\x72\xf7\x77\xeb\xb0\x2b\xbd\x2d\xd4\x6e\x60\x0f\x2b\x31\x16\xc6\xe3\x2c\xe9\xb5\x70\xc6\xef\x37\x8b\xf0\xe6\xc6\x4d\xae\x8a\x95\xf4\x2c\xa7\x86\xc7\x0f\xe4\xa9\x6e\x9f\xb1\x4e\xef\x38\x8b\x5c\xf0\x44\x17\x3d\xff\xbb\xe2\x67\x00\x00\x00\xff\xff\x8b\x20\x22\x7f\x12\x02\x00\x00")

func migrations1668845636_settingsUpSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations1668845636_settingsUpSql,
		"migrations/1668845636_settings.up.sql",
	)
}

func migrations1668845636_settingsUpSql() (*asset, error) {
	bytes, err := migrations1668845636_settingsUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/1668845636_settings.up.sql", size: 530, mode: os.FileMode(0664), modTime: time.Unix(1669023217, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x5b, 0x57, 0xe4, 0xf2, 0x27, 0x7f, 0x1d, 0x60, 0x68, 0xf0, 0x9a, 0x8e, 0x90, 0xa9, 0xa, 0x39, 0xbd, 0x14, 0x15, 0x4c, 0xa, 0x2a, 0x7b, 0x1e, 0xd9, 0xc7, 0xaa, 0x8d, 0x24, 0x81, 0x4, 0xb8}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"migrations/1633685677_init.down.sql":     migrations1633685677_initDownSql,
	"migrations/1633685677_init.up.sql":       migrations1633685677_initUpSql,
	"migrations/1668845636_settings.down.sql": migrations1668845636_settingsDownSql,
	"migrations/1668845636_settings.up.sql":   migrations1668845636_settingsUpSql,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"migrations": {nil, map[string]*bintree{
		"1633685677_init.down.sql":     {migrations1633685677_initDownSql, map[string]*bintree{}},
		"1633685677_init.up.sql":       {migrations1633685677_initUpSql, map[string]*bintree{}},
		"1668845636_settings.down.sql": {migrations1668845636_settingsDownSql, map[string]*bintree{}},
		"1668845636_settings.up.sql":   {migrations1668845636_settingsUpSql, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
